### ISSUE TITLE
[BUG] Magisk module cannot be installed

### ISSUE THREAD

**Issue by bolabola6789** [MustardChef/WSABuilds#318] opened 2024-03-01 04:11 UTC
### Describe the bug

Every magisk module I tried failed to install. The installation screen in magisk claims the module was sucessfully installed, 
![image](https://github.com/MustardChef/WSABuilds/assets/105188534/480d2c94-070f-4206-a93f-e4c58a923001)
but after I click on "reboot", the module list is empty
![image](https://github.com/MustardChef/WSABuilds/assets/105188534/54315b45-2c50-47c6-a1ff-b9a9defc5469)
I did click yes in the additional setup required screen when first installed WSA, so the problem might be from there?

2 most recent logcat:
[20240301035717.log](https://github.com/MustardChef/WSABuilds/files/14456305/20240301035717.log)
[20240301040356.log](https://github.com/MustardChef/WSABuilds/files/14456315/20240301040356.log)

### Steps to reproduce the issue

1. Open magisk
2. Install a module, screen says "Done"
3. Click reboot

### Expected behaviour

Module is installed

### Downloaded Build Of WSA

WSA_2311.40000.5.0_x64_Release-Nightly-with-Magisk-26.4-stable-MindTheGapps-13.0_Windows_10

### Windows build number

19045.4046

### PC Specification

![image](https://github.com/MustardChef/WSABuilds/assets/105188534/8bfdb894-146f-40ab-8d26-4c31d19c163d)
The computer meets Windows 11 requirements.

### Additional context

Tried on another T460 with 6th gen core i5, same problem

**Comment by MustardChef** [comment] 2024-03-01 04:20
Duplicate of https://github.com/MustardChef/WSABuilds/issues/154

**Closed** 2024-03-01 04:59 UTC

**Comment by landall** [comment] 2024-03-05 19:14
> Thanks, module installed succesfully

how do you solve it?

**Comment by bolabola6789** [comment] 2024-03-06 09:46
> > Thanks, module installed succesfully
> 
> how do you solve it?

Just read the issue that the author referenced, the guide is pretty detailed

**Comment by landall** [comment] 2024-03-06 17:25
> Just read the issue that the author referenced, the guide is pretty detailed

failed by the handbook but I try another way and finish it.
